import { expect, test } from '@playwright/test';

import { DashboardPage } from './pages/DashboardPage.js';

const uniqueSuffix = `${Date.now()}`;
const FLAG_KEY = `smoke_flag_${uniqueSuffix}`;

async function failOnNetworkErrors(page) {
  const failures = [];

  page.on('response', (response) => {
    if (response.status() >= 400) {
      failures.push(`HTTP ${response.status()} for ${response.url()}`);
    }
  });

  page.on('pageerror', (error) => {
    failures.push(`Page error: ${error.message}`);
  });

  page.on('console', (message) => {
    if (message.type() === 'error') {
      failures.push(`Console error: ${message.text()}`);
    }
  });

  return {
    async assertNoErrors() {
      await page.waitForFunction(() => document.readyState === 'complete');
      if (failures.length > 0) {
        throw new Error(`Detected application errors:\n${failures.join('\n')}`);
      }
    },
  };
}

test.describe('Feature Flag smoke test', () => {
  test('loads the dashboard, creates a flag, and returns to empty state after cleanup', async ({ page }, testInfo) => {
    const dashboardPage = new DashboardPage(page);
    const networkMonitor = await failOnNetworkErrors(page);

    try {
      await dashboardPage.goto();
      await dashboardPage.waitForDashboardReady();
      await networkMonitor.assertNoErrors();

      await expect(page.getByText('Feature Flag Management')).toBeVisible();
      await dashboardPage.expectNoFailedToFetch();
      await dashboardPage.expectSummaryCardsVisible();

      await expect.poll(async () => (await dashboardPage.getCardValue('Total Feature Flags'))?.trim(), {
        timeout: 15000,
      }).not.toBe('—');

      await dashboardPage.openCreateFlagModal();
      await dashboardPage.createFlag({
        key: FLAG_KEY,
        description: 'Smoke test flag generated by Playwright',
        ownerTeam: 'Platform',
        environment: 'Development',
        enabled: true,
      });

      await dashboardPage.expectFlagVisible(FLAG_KEY);
      await expect(page.getByText(`Flag '${FLAG_KEY}' created successfully.`)).toBeVisible();
      await expect(await dashboardPage.getCardValue('Total Feature Flags')).toContain('1');
      await expect(await dashboardPage.getCardValue('Enabled Feature Flags')).toContain('1');
      await expect(await dashboardPage.getCardValue('Disabled Feature Flags')).toContain('0');

      await dashboardPage.deleteFlag(FLAG_KEY);
      await expect(page.getByText(FLAG_KEY)).toHaveCount(0);
      await dashboardPage.expectEmptyState();
      await expect(await dashboardPage.getCardValue('Total Feature Flags')).toContain('0');
      await expect(await dashboardPage.getCardValue('Enabled Feature Flags')).toContain('0');
      await expect(await dashboardPage.getCardValue('Disabled Feature Flags')).toContain('0');

      await testInfo.attach('final-screenshot', {
        body: await page.screenshot({ fullPage: true }),
        contentType: 'image/png',
      });
    } catch (error) {
      if (!page.isClosed()) {
        await testInfo.attach('failure-screenshot', {
          body: await page.screenshot({ fullPage: true }),
          contentType: 'image/png',
        });
      }
      throw error;
    }
  });
});
